//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimberDraw.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToolTips {
            get {
                return ((bool)(this["ToolTips"]));
            }
            set {
                this["ToolTips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasJoinery {
            get {
                return ((bool)(this["HasJoinery"]));
            }
            set {
                this["HasJoinery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeletePolylines {
            get {
                return ((bool)(this["DeletePolylines"]));
            }
            set {
                this["DeletePolylines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveHt {
            get {
                return ((double)(this["EaveHt"]));
            }
            set {
                this["EaveHt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Span {
            get {
                return ((double)(this["Span"]));
            }
            set {
                this["Span"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RoofPitchRun {
            get {
                return ((double)(this["RoofPitchRun"]));
            }
            set {
                this["RoofPitchRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RoofPitchRise {
            get {
                return ((double)(this["RoofPitchRise"]));
            }
            set {
                this["RoofPitchRise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BayWidth {
            get {
                return ((double)(this["BayWidth"]));
            }
            set {
                this["BayWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Make3D {
            get {
                return ((bool)(this["Make3D"]));
            }
            set {
                this["Make3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtHt {
            get {
                return ((double)(this["FlrGirtHt"]));
            }
            set {
                this["FlrGirtHt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TrussType {
            get {
                return ((int)(this["TrussType"]));
            }
            set {
                this["TrussType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BentNumber {
            get {
                return ((int)(this["BentNumber"]));
            }
            set {
                this["BentNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WallNumber {
            get {
                return ((int)(this["WallNumber"]));
            }
            set {
                this["WallNumber"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public string WallAlpha {
            get {
                return ((string)(this["WallAlpha"]));
            }
            set {
                this["WallAlpha"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BraceStrutPlacement {
            get {
                return ((int)(this["BraceStrutPlacement"]));
            }
            set {
                this["BraceStrutPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasPost {
            get {
                return ((bool)(this["HBHasPost"]));
            }
            set {
                this["HBHasPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBPostWidth {
            get {
                return ((double)(this["HBPostWidth"]));
            }
            set {
                this["HBPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBPostDepth {
            get {
                return ((double)(this["HBPostDepth"]));
            }
            set {
                this["HBPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasHbeam {
            get {
                return ((bool)(this["HBHasHbeam"]));
            }
            set {
                this["HBHasHbeam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBeamWidth {
            get {
                return ((double)(this["HBeamWidth"]));
            }
            set {
                this["HBeamWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBeamDepth {
            get {
                return ((double)(this["HBeamDepth"]));
            }
            set {
                this["HBeamDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasHPost {
            get {
                return ((bool)(this["HBHasHPost"]));
            }
            set {
                this["HBHasHPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HPostWidth {
            get {
                return ((double)(this["HPostWidth"]));
            }
            set {
                this["HPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HPostDepth {
            get {
                return ((double)(this["HPostDepth"]));
            }
            set {
                this["HPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasKPost {
            get {
                return ((bool)(this["HBHasKPost"]));
            }
            set {
                this["HBHasKPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBKPostWidth {
            get {
                return ((double)(this["HBKPostWidth"]));
            }
            set {
                this["HBKPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBKPostDepth {
            get {
                return ((double)(this["HBKPostDepth"]));
            }
            set {
                this["HBKPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasRafter {
            get {
                return ((bool)(this["HBHasRafter"]));
            }
            set {
                this["HBHasRafter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBRafterWidth {
            get {
                return ((double)(this["HBRafterWidth"]));
            }
            set {
                this["HBRafterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBRafterDepth {
            get {
                return ((double)(this["HBRafterDepth"]));
            }
            set {
                this["HBRafterDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasHBGirt {
            get {
                return ((bool)(this["HBHasHBGirt"]));
            }
            set {
                this["HBHasHBGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBGirtWidth {
            get {
                return ((double)(this["HBGirtWidth"]));
            }
            set {
                this["HBGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBGirtDepth {
            get {
                return ((double)(this["HBGirtDepth"]));
            }
            set {
                this["HBGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasBrace {
            get {
                return ((bool)(this["HBHasBrace"]));
            }
            set {
                this["HBHasBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBraceWidth {
            get {
                return ((double)(this["HBBraceWidth"]));
            }
            set {
                this["HBBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBraceDepth {
            get {
                return ((double)(this["HBBraceDepth"]));
            }
            set {
                this["HBBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBraceLength {
            get {
                return ((double)(this["HBBraceLength"]));
            }
            set {
                this["HBBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasBayGirt {
            get {
                return ((bool)(this["HBHasBayGirt"]));
            }
            set {
                this["HBHasBayGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBayGirtWidth {
            get {
                return ((double)(this["HBBayGirtWidth"]));
            }
            set {
                this["HBBayGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBayGirtDepth {
            get {
                return ((double)(this["HBBayGirtDepth"]));
            }
            set {
                this["HBBayGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasBGBrace {
            get {
                return ((bool)(this["HBHasBGBrace"]));
            }
            set {
                this["HBHasBGBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBGBraceWidth {
            get {
                return ((double)(this["HBBGBraceWidth"]));
            }
            set {
                this["HBBGBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBGBraceDepth {
            get {
                return ((double)(this["HBBGBraceDepth"]));
            }
            set {
                this["HBBGBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBBGBraceLength {
            get {
                return ((double)(this["HBBGBraceLength"]));
            }
            set {
                this["HBBGBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasFlrGirt {
            get {
                return ((bool)(this["HBHasFlrGirt"]));
            }
            set {
                this["HBHasFlrGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrGirtWidth {
            get {
                return ((double)(this["HBFlrGirtWidth"]));
            }
            set {
                this["HBFlrGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrGirtDepth {
            get {
                return ((double)(this["HBFlrGirtDepth"]));
            }
            set {
                this["HBFlrGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrGirtHt {
            get {
                return ((double)(this["HBFlrGirtHt"]));
            }
            set {
                this["HBFlrGirtHt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HBHasFlrBrace {
            get {
                return ((bool)(this["HBHasFlrBrace"]));
            }
            set {
                this["HBHasFlrBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrBraceWidth {
            get {
                return ((double)(this["HBFlrBraceWidth"]));
            }
            set {
                this["HBFlrBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrBraceDepth {
            get {
                return ((double)(this["HBFlrBraceDepth"]));
            }
            set {
                this["HBFlrBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double HBFlrBraceLength {
            get {
                return ((double)(this["HBFlrBraceLength"]));
            }
            set {
                this["HBFlrBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HBDivisor {
            get {
                return ((int)(this["HBDivisor"]));
            }
            set {
                this["HBDivisor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasPost {
            get {
                return ((bool)(this["KPHasPost"]));
            }
            set {
                this["KPHasPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPPostWidth {
            get {
                return ((double)(this["KPPostWidth"]));
            }
            set {
                this["KPPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPPostDepth {
            get {
                return ((double)(this["KPPostDepth"]));
            }
            set {
                this["KPPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasGirt {
            get {
                return ((bool)(this["KPHasGirt"]));
            }
            set {
                this["KPHasGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPGirtWidth {
            get {
                return ((double)(this["KPGirtWidth"]));
            }
            set {
                this["KPGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPGirtDepth {
            get {
                return ((double)(this["KPGirtDepth"]));
            }
            set {
                this["KPGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasRafter {
            get {
                return ((bool)(this["KPHasRafter"]));
            }
            set {
                this["KPHasRafter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPRafterWidth {
            get {
                return ((double)(this["KPRafterWidth"]));
            }
            set {
                this["KPRafterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPRafterDepth {
            get {
                return ((double)(this["KPRafterDepth"]));
            }
            set {
                this["KPRafterDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasKPost {
            get {
                return ((bool)(this["KPHasKPost"]));
            }
            set {
                this["KPHasKPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPKpostWidth {
            get {
                return ((double)(this["KPKpostWidth"]));
            }
            set {
                this["KPKpostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPKpostDepth {
            get {
                return ((double)(this["KPKpostDepth"]));
            }
            set {
                this["KPKpostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasStrut {
            get {
                return ((bool)(this["KPHasStrut"]));
            }
            set {
                this["KPHasStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPStrutWidth {
            get {
                return ((double)(this["KPStrutWidth"]));
            }
            set {
                this["KPStrutWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double KPStrutAngle {
            get {
                return ((double)(this["KPStrutAngle"]));
            }
            set {
                this["KPStrutAngle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public double KPBraceAngle {
            get {
                return ((double)(this["KPBraceAngle"]));
            }
            set {
                this["KPBraceAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPStrutDepth {
            get {
                return ((double)(this["KPStrutDepth"]));
            }
            set {
                this["KPStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasVStrut {
            get {
                return ((bool)(this["KPHasVStrut"]));
            }
            set {
                this["KPHasVStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPVStrutWidth {
            get {
                return ((double)(this["KPVStrutWidth"]));
            }
            set {
                this["KPVStrutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPVStrutDepth {
            get {
                return ((double)(this["KPVStrutDepth"]));
            }
            set {
                this["KPVStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasBrace {
            get {
                return ((bool)(this["KPHasBrace"]));
            }
            set {
                this["KPHasBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPBraceWidth {
            get {
                return ((double)(this["KPBraceWidth"]));
            }
            set {
                this["KPBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPBraceDepth {
            get {
                return ((double)(this["KPBraceDepth"]));
            }
            set {
                this["KPBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPBraceLength {
            get {
                return ((double)(this["KPBraceLength"]));
            }
            set {
                this["KPBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasFlrGirt {
            get {
                return ((bool)(this["KPHasFlrGirt"]));
            }
            set {
                this["KPHasFlrGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrGirtWidth {
            get {
                return ((double)(this["KPFlrGirtWidth"]));
            }
            set {
                this["KPFlrGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrGirtDepth {
            get {
                return ((double)(this["KPFlrGirtDepth"]));
            }
            set {
                this["KPFlrGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrGirtHt {
            get {
                return ((double)(this["KPFlrGirtHt"]));
            }
            set {
                this["KPFlrGirtHt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPHasFlrBrace {
            get {
                return ((bool)(this["KPHasFlrBrace"]));
            }
            set {
                this["KPHasFlrBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrBraceWidth {
            get {
                return ((double)(this["KPFlrBraceWidth"]));
            }
            set {
                this["KPFlrBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrBraceDepth {
            get {
                return ((double)(this["KPFlrBraceDepth"]));
            }
            set {
                this["KPFlrBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPFlrBraceLength {
            get {
                return ((double)(this["KPFlrBraceLength"]));
            }
            set {
                this["KPFlrBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasPost {
            get {
                return ((bool)(this["QPHasPost"]));
            }
            set {
                this["QPHasPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPPostWidth {
            get {
                return ((double)(this["QPPostWidth"]));
            }
            set {
                this["QPPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPPostDepth {
            get {
                return ((double)(this["QPPostDepth"]));
            }
            set {
                this["QPPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasGirt {
            get {
                return ((bool)(this["QPHasGirt"]));
            }
            set {
                this["QPHasGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPGirtWidth {
            get {
                return ((double)(this["QPGirtWidth"]));
            }
            set {
                this["QPGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPGirtDepth {
            get {
                return ((double)(this["QPGirtDepth"]));
            }
            set {
                this["QPGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasRafter {
            get {
                return ((bool)(this["QPHasRafter"]));
            }
            set {
                this["QPHasRafter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPRafterWidth {
            get {
                return ((double)(this["QPRafterWidth"]));
            }
            set {
                this["QPRafterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPRafterDepth {
            get {
                return ((double)(this["QPRafterDepth"]));
            }
            set {
                this["QPRafterDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasQPost {
            get {
                return ((bool)(this["QPHasQPost"]));
            }
            set {
                this["QPHasQPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPostWidth {
            get {
                return ((double)(this["QPQPostWidth"]));
            }
            set {
                this["QPQPostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPostDepth {
            get {
                return ((double)(this["QPQPostDepth"]));
            }
            set {
                this["QPQPostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasStrut {
            get {
                return ((bool)(this["QPHasStrut"]));
            }
            set {
                this["QPHasStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPStrutWidth {
            get {
                return ((double)(this["QPStrutWidth"]));
            }
            set {
                this["QPStrutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPStrutDepth {
            get {
                return ((double)(this["QPStrutDepth"]));
            }
            set {
                this["QPStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasQPGirt {
            get {
                return ((bool)(this["QPHasQPGirt"]));
            }
            set {
                this["QPHasQPGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPGirtWidth {
            get {
                return ((double)(this["QPQPGirtWidth"]));
            }
            set {
                this["QPQPGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPGirtDepth {
            get {
                return ((double)(this["QPQPGirtDepth"]));
            }
            set {
                this["QPQPGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasBrace {
            get {
                return ((bool)(this["QPHasBrace"]));
            }
            set {
                this["QPHasBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPBraceWidth {
            get {
                return ((double)(this["QPBraceWidth"]));
            }
            set {
                this["QPBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPBraceDepth {
            get {
                return ((double)(this["QPBraceDepth"]));
            }
            set {
                this["QPBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPBraceLength {
            get {
                return ((double)(this["QPBraceLength"]));
            }
            set {
                this["QPBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasQPBrace {
            get {
                return ((bool)(this["QPHasQPBrace"]));
            }
            set {
                this["QPHasQPBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPBraceWidth {
            get {
                return ((double)(this["QPQPBraceWidth"]));
            }
            set {
                this["QPQPBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPBraceDepth {
            get {
                return ((double)(this["QPQPBraceDepth"]));
            }
            set {
                this["QPQPBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPQPBraceLength {
            get {
                return ((double)(this["QPQPBraceLength"]));
            }
            set {
                this["QPQPBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasFlrGirt {
            get {
                return ((bool)(this["QPHasFlrGirt"]));
            }
            set {
                this["QPHasFlrGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrGirtWidth {
            get {
                return ((double)(this["QPFlrGirtWidth"]));
            }
            set {
                this["QPFlrGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrGirtDepth {
            get {
                return ((double)(this["QPFlrGirtDepth"]));
            }
            set {
                this["QPFlrGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrGirtHt {
            get {
                return ((double)(this["QPFlrGirtHt"]));
            }
            set {
                this["QPFlrGirtHt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPHasFlrBrace {
            get {
                return ((bool)(this["QPHasFlrBrace"]));
            }
            set {
                this["QPHasFlrBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrBraceWidth {
            get {
                return ((double)(this["QPFlrBraceWidth"]));
            }
            set {
                this["QPFlrBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrBraceDepth {
            get {
                return ((double)(this["QPFlrBraceDepth"]));
            }
            set {
                this["QPFlrBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPFlrBraceLength {
            get {
                return ((double)(this["QPFlrBraceLength"]));
            }
            set {
                this["QPFlrBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPTHasGirt {
            get {
                return ((bool)(this["KPTHasGirt"]));
            }
            set {
                this["KPTHasGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTGirtWidth {
            get {
                return ((double)(this["KPTGirtWidth"]));
            }
            set {
                this["KPTGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTGirtDepth {
            get {
                return ((double)(this["KPTGirtDepth"]));
            }
            set {
                this["KPTGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPTHasRafter {
            get {
                return ((bool)(this["KPTHasRafter"]));
            }
            set {
                this["KPTHasRafter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTRafterWidth {
            get {
                return ((double)(this["KPTRafterWidth"]));
            }
            set {
                this["KPTRafterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTRafterDepth {
            get {
                return ((double)(this["KPTRafterDepth"]));
            }
            set {
                this["KPTRafterDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPTHasKpost {
            get {
                return ((bool)(this["KPTHasKpost"]));
            }
            set {
                this["KPTHasKpost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTKpostWidth {
            get {
                return ((double)(this["KPTKpostWidth"]));
            }
            set {
                this["KPTKpostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTKpostDepth {
            get {
                return ((double)(this["KPTKpostDepth"]));
            }
            set {
                this["KPTKpostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPTHasStrut {
            get {
                return ((bool)(this["KPTHasStrut"]));
            }
            set {
                this["KPTHasStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTStrutWidth {
            get {
                return ((double)(this["KPTStrutWidth"]));
            }
            set {
                this["KPTStrutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTStrutDepth {
            get {
                return ((double)(this["KPTStrutDepth"]));
            }
            set {
                this["KPTStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KPTHasVStrut {
            get {
                return ((bool)(this["KPTHasVStrut"]));
            }
            set {
                this["KPTHasVStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTVStrutWidth {
            get {
                return ((double)(this["KPTVStrutWidth"]));
            }
            set {
                this["KPTVStrutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KPTVStrutDepth {
            get {
                return ((double)(this["KPTVStrutDepth"]));
            }
            set {
                this["KPTVStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasGirt {
            get {
                return ((bool)(this["QPTHasGirt"]));
            }
            set {
                this["QPTHasGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTGirtWidth {
            get {
                return ((double)(this["QPTGirtWidth"]));
            }
            set {
                this["QPTGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTGirtDepth {
            get {
                return ((double)(this["QPTGirtDepth"]));
            }
            set {
                this["QPTGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasRafter {
            get {
                return ((bool)(this["QPTHasRafter"]));
            }
            set {
                this["QPTHasRafter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTRafterWidth {
            get {
                return ((double)(this["QPTRafterWidth"]));
            }
            set {
                this["QPTRafterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTRafterDepth {
            get {
                return ((double)(this["QPTRafterDepth"]));
            }
            set {
                this["QPTRafterDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasQpost {
            get {
                return ((bool)(this["QPTHasQpost"]));
            }
            set {
                this["QPTHasQpost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTQpostWidth {
            get {
                return ((double)(this["QPTQpostWidth"]));
            }
            set {
                this["QPTQpostWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTQpostDepth {
            get {
                return ((double)(this["QPTQpostDepth"]));
            }
            set {
                this["QPTQpostDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasStrut {
            get {
                return ((bool)(this["QPTHasStrut"]));
            }
            set {
                this["QPTHasStrut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTStrutWidth {
            get {
                return ((double)(this["QPTStrutWidth"]));
            }
            set {
                this["QPTStrutWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTStrutDepth {
            get {
                return ((double)(this["QPTStrutDepth"]));
            }
            set {
                this["QPTStrutDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasQPGirt {
            get {
                return ((bool)(this["QPTHasQPGirt"]));
            }
            set {
                this["QPTHasQPGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTUpperGirtWidth {
            get {
                return ((double)(this["QPTUpperGirtWidth"]));
            }
            set {
                this["QPTUpperGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTUpperGirtDepth {
            get {
                return ((double)(this["QPTUpperGirtDepth"]));
            }
            set {
                this["QPTUpperGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QPTHasQPBrace {
            get {
                return ((bool)(this["QPTHasQPBrace"]));
            }
            set {
                this["QPTHasQPBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTQPBraceWidth {
            get {
                return ((double)(this["QPTQPBraceWidth"]));
            }
            set {
                this["QPTQPBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTQPBraceDepth {
            get {
                return ((double)(this["QPTQPBraceDepth"]));
            }
            set {
                this["QPTQPBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double QPTQPBraceLength {
            get {
                return ((double)(this["QPTQPBraceLength"]));
            }
            set {
                this["QPTQPBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasRidge {
            get {
                return ((bool)(this["HasRidge"]));
            }
            set {
                this["HasRidge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RidgeWidth {
            get {
                return ((double)(this["RidgeWidth"]));
            }
            set {
                this["RidgeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RidgeDepth {
            get {
                return ((double)(this["RidgeDepth"]));
            }
            set {
                this["RidgeDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasRidgeBrace {
            get {
                return ((bool)(this["HasRidgeBrace"]));
            }
            set {
                this["HasRidgeBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RidgeBraceWidth {
            get {
                return ((double)(this["RidgeBraceWidth"]));
            }
            set {
                this["RidgeBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RidgeBraceDepth {
            get {
                return ((double)(this["RidgeBraceDepth"]));
            }
            set {
                this["RidgeBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RidgeBraceLength {
            get {
                return ((double)(this["RidgeBraceLength"]));
            }
            set {
                this["RidgeBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasEaveGirt {
            get {
                return ((bool)(this["HasEaveGirt"]));
            }
            set {
                this["HasEaveGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveGirtWidth {
            get {
                return ((double)(this["EaveGirtWidth"]));
            }
            set {
                this["EaveGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveGirtDepth {
            get {
                return ((double)(this["EaveGirtDepth"]));
            }
            set {
                this["EaveGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasEaveGirtBrace {
            get {
                return ((bool)(this["HasEaveGirtBrace"]));
            }
            set {
                this["HasEaveGirtBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveGirtBraceWidth {
            get {
                return ((double)(this["EaveGirtBraceWidth"]));
            }
            set {
                this["EaveGirtBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveGirtBraceDepth {
            get {
                return ((double)(this["EaveGirtBraceDepth"]));
            }
            set {
                this["EaveGirtBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double EaveGirtBraceLength {
            get {
                return ((double)(this["EaveGirtBraceLength"]));
            }
            set {
                this["EaveGirtBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasPurlins {
            get {
                return ((bool)(this["HasPurlins"]));
            }
            set {
                this["HasPurlins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PurlinWidth {
            get {
                return ((double)(this["PurlinWidth"]));
            }
            set {
                this["PurlinWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PurlinDepth {
            get {
                return ((double)(this["PurlinDepth"]));
            }
            set {
                this["PurlinDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasCommons {
            get {
                return ((bool)(this["HasCommons"]));
            }
            set {
                this["HasCommons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CommonWidth {
            get {
                return ((double)(this["CommonWidth"]));
            }
            set {
                this["CommonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CommonDepth {
            get {
                return ((double)(this["CommonDepth"]));
            }
            set {
                this["CommonDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateBayMembers {
            get {
                return ((bool)(this["GenerateBayMembers"]));
            }
            set {
                this["GenerateBayMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasFlrGirt {
            get {
                return ((bool)(this["HasFlrGirt"]));
            }
            set {
                this["HasFlrGirt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtWidth {
            get {
                return ((double)(this["FlrGirtWidth"]));
            }
            set {
                this["FlrGirtWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtDepth {
            get {
                return ((double)(this["FlrGirtDepth"]));
            }
            set {
                this["FlrGirtDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasFlrGirtBrace {
            get {
                return ((bool)(this["HasFlrGirtBrace"]));
            }
            set {
                this["HasFlrGirtBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtBraceWidth {
            get {
                return ((double)(this["FlrGirtBraceWidth"]));
            }
            set {
                this["FlrGirtBraceWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtBraceDepth {
            get {
                return ((double)(this["FlrGirtBraceDepth"]));
            }
            set {
                this["FlrGirtBraceDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FlrGirtBraceLength {
            get {
                return ((double)(this["FlrGirtBraceLength"]));
            }
            set {
                this["FlrGirtBraceLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RoofLoad {
            get {
                return ((double)(this["RoofLoad"]));
            }
            set {
                this["RoofLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AllowableDeflection {
            get {
                return ((int)(this["AllowableDeflection"]));
            }
            set {
                this["AllowableDeflection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Emod {
            get {
                return ((double)(this["Emod"]));
            }
            set {
                this["Emod"] = value;
            }
        }

        // ---- Frame params UI (TFrame model) ----

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96,144")]
        public string BaySchedule {
            get {
                return ((string)(this["BaySchedule"]));
            }
            set {
                this["BaySchedule"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CommonMode {
            get {
                return ((int)(this["CommonMode"]));
            }
            set {
                this["CommonMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CommonCount {
            get {
                return ((int)(this["CommonCount"]));
            }
            set {
                this["CommonCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double CommonSpacing {
            get {
                return ((double)(this["CommonSpacing"]));
            }
            set {
                this["CommonSpacing"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PurlinMode {
            get {
                return ((int)(this["PurlinMode"]));
            }
            set {
                this["PurlinMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PurlinCount {
            get {
                return ((int)(this["PurlinCount"]));
            }
            set {
                this["PurlinCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public double PurlinSpacing {
            get {
                return ((double)(this["PurlinSpacing"]));
            }
            set {
                this["PurlinSpacing"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameSpecJson {
            get {
                return ((string)(this["FrameSpecJson"]));
            }
            set {
                this["FrameSpecJson"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScribeFolder {
            get {
                return ((string)(this["ScribeFolder"]));
            }
            set {
                this["ScribeFolder"] = value;
            }
        }

        // ---- Managed timber palette (TPanel) ----
        // CSV of named sections, one per entry as "type:width:depth" (e.g. "Post:8:8").
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Post:8:8,Girt:6:8,Rafter:5:7,Brace:4:6,Joist:6:8,Summer:8:10")]
        public string TimberSections {
            get {
                return ((string)(this["TimberSections"]));
            }
            set {
                this["TimberSections"] = value;
            }
        }

        // Index of the currently selected section in TimberSections.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentSection {
            get {
                return ((int)(this["CurrentSection"]));
            }
            set {
                this["CurrentSection"] = value;
            }
        }

        // Knee-brace spec for TJoin: "foot:head:checkedMask" (mask = two of F/H/A, e.g. "FH").
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:18:FH")]
        public string BraceSpec {
            get {
                return ((string)(this["BraceSpec"]));
            }
            set {
                this["BraceSpec"] = value;
            }
        }

        // Rough-in bent type for TRoughIn: KingPost|QueenPost|HammerBeam|KingPostTruss|QueenPostTruss.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KingPost")]
        public string RoughInType {
            get {
                return ((string)(this["RoughInType"]));
            }
            set {
                this["RoughInType"] = value;
            }
        }

        // Path to the production-default .framespec the FrameTree seeds a New frame from (blank = empty).
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultFramePath {
            get {
                return ((string)(this["DefaultFramePath"]));
            }
            set {
                this["DefaultFramePath"] = value;
            }
        }

        // Per-type bent/bay default templates: a JSON dictionary key("Bent:KingPost"/"Bay:Purlins") ->
        // single-element frame JSON, applied when a new bent/bay of that type is typed.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TypeDefaultsJson {
            get {
                return ((string)(this["TypeDefaultsJson"]));
            }
            set {
                this["TypeDefaultsJson"] = value;
            }
        }

        // Named bent/bay template library: a JSON dictionary name -> { type, single-element frame JSON },
        // applied explicitly from the tree menu (the per-type default lives in TypeDefaultsJson).
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemplateLibraryJson {
            get {
                return ((string)(this["TemplateLibraryJson"]));
            }
            set {
                this["TemplateLibraryJson"] = value;
            }
        }

        // Per-joint-type user default specs: a JSON dictionary key(preset name, e.g. "Box tenon") ->
        // spec-struct JSON (IncludeFields). Read by JointDefaults; factory value when a key is absent.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JointDefaultsJson {
            get {
                return ((string)(this["JointDefaultsJson"]));
            }
            set {
                this["JointDefaultsJson"] = value;
            }
        }
    }
}
